// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVFxZmojqs2Sv_frJXhnWwGVkIw_Dr9EY',
    appId: '1:71458725198:web:5694e31acdf02a8ca0d21f',
    messagingSenderId: '71458725198',
    projectId: 'calmee-8011c',
    authDomain: 'calmee-8011c.firebaseapp.com',
    storageBucket: 'calmee-8011c.firebasestorage.app',
    measurementId: 'G-00Q037XKR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqTjzpdaJK6HM2O8ZpJ6wFb_wbwW8-ecY',
    appId: '1:71458725198:android:26fd5a342925ead7a0d21f',
    messagingSenderId: '71458725198',
    projectId: 'calmee-8011c',
    storageBucket: 'calmee-8011c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvmz17i4GxFyLREveM0igwK7AuGcVvwSs',
    appId: '1:71458725198:ios:9084db04937e7924a0d21f',
    messagingSenderId: '71458725198',
    projectId: 'calmee-8011c',
    storageBucket: 'calmee-8011c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvmz17i4GxFyLREveM0igwK7AuGcVvwSs',
    appId: '1:71458725198:ios:9084db04937e7924a0d21f',
    messagingSenderId: '71458725198',
    projectId: 'calmee-8011c',
    storageBucket: 'calmee-8011c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVFxZmojqs2Sv_frJXhnWwGVkIw_Dr9EY',
    appId: '1:71458725198:web:294f3ef3e8fd41f5a0d21f',
    messagingSenderId: '71458725198',
    projectId: 'calmee-8011c',
    authDomain: 'calmee-8011c.firebaseapp.com',
    storageBucket: 'calmee-8011c.firebasestorage.app',
    measurementId: 'G-M75RWR4X0E',
  );
}
